[colors.primary]
background = '#0c0c0c'
foreground = '#F4f4f4'

[colors.normal]
black = '#241F31'
red = '#EF3453'
green = '#58EF7E'
yellow = '#F5DA11'
blue = '#2D86F3'
magenta = '#F822C2'
cyan = '#24DBEF'
white = '#E2E2E2'

[colors.bright]
black = '#5E5C64'
red = '#EF3453'
green = '#58EF7E'
yellow = '#F5DA11'
blue = '#2D86F3'
magenta = '#F822C2'
cyan = '#24DBEF'
white = '#F4F4F4'

[window]
opacity = 1
