
[colors]
background = '#0c0c0c'
foreground = '#f4f4f4'
cursor_bg = '#f4f4f4'
cursor_fg = '#000000'
cursor_border = '#f4f4f4'
selection_bg = '#1a53ac'
selection_fg = '#e6edf3'
split = '#333333'

ansi = [
    '#241f31',
    '#EF3453',
    '#58EF7E',
    '#F5DA11',
    '#2D86F3',
    '#F822C2',
    '#24DBEF',
    '#E2E2E2',
]
brights = [
    '#5e5c64',
    '#EF3453',
    '#58EF7E',
    '#F5DA11',
    '#2D86F3',
    '#F822C2',
    '#24DBEF',
    '#f4f4f4',
]

[colors.tab_bar]
background = "#2d2d2d"

[colors.tab_bar.active_tab]
bg_color = '#0c0c0c'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#2d2d2d'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#2d2d2d'
fg_color = '#ffffff'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'


[metadata]
name = 'Noir'
